# Generated by Django 4.1.5 on 2023-05-24 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
