# Generated by Django 4.1.5 on 2023-05-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date',
            new_name='created_at',
        ),
    ]
