# Generated by Django 4.1.5 on 2023-05-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_date_sale_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_added',
            new_name='date',
        ),
    ]
